version: "2"
services:
  redis:
    image: redis:latest
    container_name: "redis-dock"
    user: "redis"
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      -  scrumblr-net
  node:
    image: "scrumblr-protected:latest"
    container_name: "scrumblr-protected"
    user: "node"
    ports:
      - "1000:1000"
    volumes:
      - .:/app
      - /app/node_modules
    command: nodemon server.js --server:port=1000 --redis:url=redis://redis-dock:6379
    networks:
      - scrumblr-net
networks:
    scrumblr-net:
      driver: bridge
      name: scrumblr-net
