version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: "redis-dock"
    user: "redis"
    ports:
      - "6379:6379"    
    networks:
      - app-network
  node:
    build: 
      context: .
      dockerfile: Dockerfile # Specifies the name of the Dockerfile
    user: "node"
    ports:
      - "1000:1000"
    networks:
      - app-network
    command: node server.js
    healthcheck:
      test: ["CMD-SHELL", "cat package.json | grep bcrypt && ls node_modules | grep bcrypt"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
