version: '3.8'
services:
  node:
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: nodemon server.js --server:port=1000 --redis:url=redis://redis-dock:6379 --inspect=0.0.0.0:9229

  nginx:
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
