version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: "redis-dock"
    user: "redis"
    ports:
      - "6379:6379"    
    networks:
      - app-network

  node:
    image: scrumblr-protected:latest
    user: "node"
    ports:
      - "1000:1000"
    networks:
      - app-network
    command: node server.js

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
