version: '3.8'
services:
  node:
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules        # Mount the local node_modules directory to /app/node_modules in the container
    # environment:
    #   - NODE_ENV=development
    command: nodemon server.js --server:port=1000 --redis:url=redis://redis-dock:6379 --inspect=0.0.0.0:9229
  nginx:
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
